version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/a
      timeout: 60
      runas: root