name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-2

      - name: Archive application
        run: |
          zip -r application.zip .

      - name: Upload to AWS S3
        run: |
          aws s3 cp application.zip s3://yellow-banana-boys/application.zip

      - name: Trigger CodeDeploy deployment
        run: |
          aws deploy create-deployment --application-name yellow-banana-boys-2024-app --deployment-group-name Production --s3-location bucket=yellow-banana-boys,key=application.zip,bundleType=zip


          # - name: Sync files to S3 bucket
          #   run: |
          #     aws s3 sync build s3://yellow-banana-boys --delete
    